# Generated by Django 4.1.7 on 2023-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video', models.FileField(upload_to='uploads/video')),
                ('documentation', models.TextField(max_length=10000)),
            ],
        ),
    ]
